#! /bin/sh

if test "$PAKE_HOME" = ""; then
  export PAKE_HOME="$PWD"
fi

echo "(in $PAKE_HOME)"
echo ""

INSTALL_DIR="$(dirname "$(test -L "$0" && readlink "$0" || echo "$0")")"
/usr/bin/env php "$INSTALL_DIR/pake.php" $@

